#! /bin/bash
#
# U.S. Geological Survey
#
# File - ncf2cbh
#
# Purpose - Docker entry-point for ncf2cbh container.
#
# Authors - Richard McDonald, Steven Markstrom,
#           Andrew Halper
#

echo "Input Dir is $NCF2CBH_IDIR"
echo "Start date is $NCF2CBH_START_DATE"
echo "File prefix is $NCF2CBH_PREFIX"

# Combine START_DATE and OP_NCF_PREFIX with an underscore
COMBINED_ARG="${NCF2CBH_START_DATE}_${NCF2CBH_PREFIX}"
echo "Combined argument is $COMBINED_ARG"

/opt/conda/bin/python \
    -u "$NHM_SOURCE_DIR/onhm-runners/ncf2cbh/ncf2cbh_gfv11b.py" \
    "$NCF2CBH_IDIR" "$COMBINED_ARG"
