#! /bin/bash
#
# U.S. Geological Survey
#
# File - ncf2cbh
#
# Purpose - Docker entry-point for ncf2cbh container.
#
# Authors - Richard McDonald, Steven Markstrom,
#           Andrew Halper
#

echo "Input Dir is $NCF2CBH_IDIR"
echo "Start date is $NCF2CBH_START_DATE"
echo "File prefix is $NCF2CBH_PREFIX"
echo "File ensemble number is $NCF2CBH_ENS_NUM"
echo "nhm_id dir is $NCF2CBH_NHMID_DIR"
echo "Mode is $NCF2CBH_MODE"

# Combine START_DATE and OP_NCF_PREFIX with an underscore
COMBINED_ARG="${NCF2CBH_START_DATE}_${NCF2CBH_PREFIX}"
echo "Combined argument is $COMBINED_ARG"

/opt/conda/bin/python \
    -u "/opt/conda/bin/ncf2cbh_gfv11_embedded.py" \
    "--wdir" "$NCF2CBH_IDIR" \
    "--prefix" "$COMBINED_ARG" \
    "--mode" "$NCF2CBH_MODE" \
    "--nhmid-dir" "$NCF2CBH_NHMID_DIR"
