#! /bin/bash
#
# U.S. Geological Survey
#
# File - ncf2cbh
#
# Purpose - Docker entry-point for ncf2cbh container.
#
# Authors - Richard McDonald, Steven Markstrom,
#           Andrew Halper
#

echo "Input Dir is $OP_NCF_IDIR"
echo "Date tag is $END_DATE"
echo "File prefix is $OP_NCF_PREFIX"

/opt/conda/bin/python \
    -u "$NHM_SOURCE_DIR/onhm-runners/ncf2cbh/ncf2cbh_gfv11b.py" \
    "$OP_NCF_IDIR" "$END_DATE" "$OP_NCF_PREFIX"
