#! /bin/bash
#
# U.S. Geological Survey
#
# File - out2ncf
#
# Purpose - Docker entry-point for out2ncf container.
#
# Authors - Richard McDonald, Steven Markstrom,
#           Andrew Halper
#

echo "The output path is $OUT_WORK_PATH"
echo "The project root path is $OUT_ROOT_PATH"

/opt/conda/bin/python \
  -u "/opt/conda/bin/out2ncf_embedded.py" \
  "--output-path" "$OUT_WORK_PATH" \
  "--root-path" "$OUT_ROOT_PATH"
  