#! /bin/bash
#
# U.S. Geological Survey
#
# File - ofp
#
# Purpose - Docker entry-point for NHM gridmetetl container.
#
# Authors - Ivan Suftin, Richard McDonald, Steven Markstrom,
#           Andrew Halper
#

echo "NHM_SOURCE_DIR is $NHM_SOURCE_DIR"
echo "START DATE is $START_DATE"
echo "END DATE is $END_DATE"
echo "INPUT FILE is $GM_INPUT_FILE"
echo "WEIGHTS FILE is $GM_WIEGHTS_FILE"
echo "OUTPATH is $OP_NCF_IDIR"

gridmetetl \
     -ds gridmet \
     -p "$START_DATE" "$END_DATE" \
     -f original \
     -i "$GM_INPUT_FILE" \
     -o "$OP_NCF_IDIR" \
     -w "$GM_WIEGHTS_FILE" \
     -fid nhm_id \
     -fm 